openapi: 3.1.0
info:
  title: Candlestick Service API
  description: API for retrieving candlestick data for financial instruments.
  contact:
    name: "Kirill Kachalov"
    url: "https://github.com/DisterDE"
  version: "1.0"
servers:
  - url: http://localhost:9000
tags:
  - name: "candlesticks"
    description: "Candlesticks endpoints"
paths:
  /candlesticks:
    get:
      tags:
        - candlesticks
      summary: Retrieve candlestick data
      description: >
        Retrieve candlestick data for a specific ISIN. 
        Requires the `isin` query parameter to specify the financial instrument.
      parameters:
        - name: isin
          in: query
          required: true
          description: ISIN (International Securities Identification Number) of the instrument.
          schema:
            type: string
            example: "US0378331005"
      responses:
        '200':
          description: A list of candlestick data.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Candlestick'
        '400':
          description: Bad request, missing or invalid ISIN.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Handler not found for the given ISIN.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Candlestick:
      type: object
      properties:
        openTimestamp:
          type: string
          format: date-time
          description: Start time of the candlestick.
          example: "2023-10-10T10:00:00Z"
        closeTimestamp:
          type: string
          format: date-time
          description: End time of the candlestick.
          example: "2023-10-10T10:01:00Z"
        openPrice:
          type: number
          format: double
          description: Opening price of the interval.
          example: 100.5
        closingPrice:
          type: number
          format: double
          description: Closing price of the interval.
          example: 101.0
        highPrice:
          type: number
          format: double
          description: Highest price within the interval.
          example: 102.0
        lowPrice:
          type: number
          format: double
          description: Lowest price within the interval.
          example: 99.5
    Error:
      type: object
      properties:
        reason:
          type: string
          description: Error reason or code.
          example: "handler_not_found"
        isin:
          type: string
          nullable: true
          description: The ISIN related to the error, if applicable.
          example: "US0378331005"