openapi: 3.1.0
info:
  title: "Candlestick API"
  description: "API for managing candlesticks for financial instruments."
  version: "1.0.0"
  contact:
    name: "Kirill Kachalov"
    url: "https://github.com/DisterDE"
servers:
  - url: "http://localhost:8080"
    description: "Local development server"
tags:
  - name: "Candlesticks"
    description: "Endpoints for working with candlesticks"
paths:
  /candlesticks:
    get:
      summary: "Retrieve candlesticks for a specific ISIN"
      description: "Returns a list of candlesticks for a given financial instrument identified by ISIN."
      tags:
        - "Candlesticks"
      parameters:
        - in: query
          name: isin
          required: true
          description: "The ISIN of the financial instrument."
          schema:
            type: string
      responses:
        '200':
          description: "A list of candlesticks."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Candlestick'
        '400':
          $ref: '#/components/responses/MissingISIN'
        '404':
          $ref: '#/components/responses/HandlerNotFound'
        '500':
          $ref: '#/components/responses/ApiException'
components:
  schemas:
    Candlestick:
      type: object
      properties:
        openTimestamp:
          type: string
          format: date-time
          description: "The opening time of the candlestick."
        closeTimestamp:
          type: string
          format: date-time
          description: "The closing time of the candlestick."
        openPrice:
          type: number
          description: "The opening price of the candlestick."
        closingPrice:
          type: number
          description: "The closing price of the candlestick."
        highPrice:
          type: number
          description: "The highest price during the candlestick's interval."
        lowPrice:
          type: number
          description: "The lowest price during the candlestick's interval."
      required:
        - openTimestamp
        - closeTimestamp
        - openPrice
        - closingPrice
        - highPrice
        - lowPrice
  responses:
    MissingISIN:
      description: "The request is missing the required ISIN parameter."
      content:
        application/json:
          example:
            reason: "missing_isin"
    HandlerNotFound:
      description: "The handler for the specified ISIN was not found."
      content:
        application/json:
          example:
            reason: "handler_not_found"
            isin: "TEST_ISIN"
    ApiException:
      description: "A server-side error occurred."
      content:
        application/json:
          example:
            reason: "internal_server_error"