services:
  partner-service:
    image: openjdk:17
    volumes:
      - ./:/app
    command: bash -c "cd /app && java -jar partner-service-1.0.1-all.jar --port=8032"
    container_name: partner-service-app
    ports:
      - "8032:8032"

  candlesticks:
    depends_on:
      - partner-service
    build:
      context: .
      dockerfile: Dockerfile
    container_name: candlesticks-app
    ports:
      - "9000:9000"